CREATE
USER runers WITH PASSWORD 'p@ssw0rd!';

GRANT CONNECT
ON DATABASE runers TO runers;

\c
runers

CREATE
EXTENSION IF NOT EXISTS citext;

GRANT ALL
ON SCHEMA public TO runers;
ALTER
DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO runers;
ALTER
DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO runers;